---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_ansible_repo: true
  ansible_verbose: true
  ansible_version: latest
  require_ruby_for_busser: true
  extra_vars:
    env: local

busser:
  ruby_bindir: /usr/bin

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    driver:
      network:
        - ["private_network", {ip: "192.168.33.10"}]
