---
- name: Install packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: packages
  when: packages is defined

- name: Disable Apache's default vhost
  command: a2dissite 000-default
  when: dissite_default == true

- name: Make sure that document root exists
  file:
    path: "{{ item.document_root }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: site
  when: site is defined
